In [1]:
import numpy as np

# Ask user for the order of the square matrix and validate input
while True:
    try:
        order = int(input("Enter the order of the square matrix (e.g., 2 for 2x2, 3 for 3x3): "))
        if order <= 0:
            print("Please enter a positive integer greater than 0.")
        else:
            break
    except ValueError:
        print("Invalid input! Please enter an integer.")

# Initialize list to store matrix elements
matrix_elements = []

# Prompt user to enter elements row-wise and validate each input
print(f"Enter {order * order} elements row-wise:")

for idx in range(order * order):
    while True:
        try:
            element = int(input(f"Element {idx + 1}: "))
            matrix_elements.append(element)
            break
        except ValueError:
            print("Invalid input! Please enter an integer.")

# Convert list to NumPy array and reshape
matrix = np.array(matrix_elements).reshape(order, order)

# Display the matrix
print("\nThe matrix is:")
print(matrix)

# Calculate sum of diagonal elements using a loop
diagonal_sum = 0
for i in range(order):
    diagonal_sum += matrix[i, i]

# Print the result
print(f"\nThe sum of diagonal elements is: {diagonal_sum}")


Enter the order of the square matrix (e.g., 2 for 2x2, 3 for 3x3):  3


Enter 9 elements row-wise:


Element 1:  4
Element 2:  1
Element 3:  3
Element 4:  7
Element 5:  2
Element 6:  5
Element 7:  9
Element 8:  2
Element 9:  1



The matrix is:
[[4 1 3]
 [7 2 5]
 [9 2 1]]

The sum of diagonal elements is: 7


In [1]:
# Import modules
import sqlite3
import pandas as pd

# Connect to an in-memory SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create tables
cursor.execute('''
CREATE TABLE Student (
    RollNo INTEGER PRIMARY KEY,
    Name TEXT,
    Marks INTEGER,
    Aadhar_Number TEXT UNIQUE,
    Address TEXT
)
''')

cursor.execute('''
CREATE TABLE Course (
    RollNo INTEGER,
    Course TEXT,
    Course_Duration TEXT,
    FOREIGN KEY (RollNo) REFERENCES Student(RollNo)
)
''')

# Insert different sample data
students = [
    (1, 'Rakesh', 22, '987654321001', 'Pune'),
    (2, 'Sneha', 78, '987654321002', 'Hyderabad'),
    (3, 'Rajiv', 42, '987654321003', 'Ahmedabad'),
    (4, 'Ritika', 90, '987654321004', 'Jaipur'),
    (5, 'Nitin', 27, '987654321005', 'Lucknow')
]
cursor.executemany('INSERT INTO Student VALUES (?, ?, ?, ?, ?)', students)

courses = [
    (1, 'BCA', '3 years'),
    (2, 'MBA', '2 years'),
    (3, 'BBA', '3 years'),
    (4, 'BCA', '3 years'),
    (5, 'BCA', '3 years')
]
cursor.executemany('INSERT INTO Course VALUES (?, ?, ?)', courses)

conn.commit()

# Perform queries and display outputs

# Calculate average marks of all students
df_avg = pd.read_sql_query('SELECT AVG(Marks) AS Average_Marks FROM Student', conn)
print("Average Marks:")
print(df_avg)

# List of names arranged in ascending order
df_names = pd.read_sql_query('SELECT Name FROM Student ORDER BY Name ASC', conn)
print("\nNames in Ascending Order:")
print(df_names)

# RollNo and names of students scoring below 30
df_below_30 = pd.read_sql_query('SELECT RollNo, Name FROM Student WHERE Marks < 30', conn)
print("\nStudents scoring below 30:")
print(df_below_30)

# RollNo of students whose names start with 'R'
df_start_R = pd.read_sql_query("SELECT RollNo FROM Student WHERE Name LIKE 'R%'", conn)
print("\nRollNo of students whose names start with 'R':")
print(df_start_R)

# RollNo of students pursuing BCA
df_bca = pd.read_sql_query("SELECT RollNo FROM Course WHERE Course = 'BCA'", conn)
print("\nRollNo of students pursuing BCA:")
print(df_bca)

# Close the database connection
conn.close()


Average Marks:
   Average_Marks
0           51.8

Names in Ascending Order:
     Name
0   Nitin
1   Rajiv
2  Rakesh
3  Ritika
4   Sneha

Students scoring below 30:
   RollNo    Name
0       1  Rakesh
1       5   Nitin

RollNo of students whose names start with 'R':
   RollNo
0       1
1       3
2       4

RollNo of students pursuing BCA:
   RollNo
0       1
1       4
2       5
